### PR TITLE
Port in megatron and apex dependencies

### PR DESCRIPTION
**Pull request by suchenzang**
Remove pip installing Megatron-LM and apex separately after porting in the relevant kernels / classes.

Megatron-LM code directly ported from https://github.com/ngoyal2707/Megatron-LM/tree/fairseq_v3

### CODE REVIEW

**Comment by ArmenAg** [comment]
This looks amazing! Is it fair to say that the imported megatron code was untouched?

**Comment by lilisierrayu** [comment]
Looks pretty good. Looking forward to real test on rsc.

**Comment by suchenzang** [comment]
@ArmenAg @lilisierrayu 7B wps on 512 GPUs varies a bit given other effects, but peak reaches the same as original (# iters, wps):
Current:
```
"178 1.16789e+06"
"179 1.59142e+06"
"180 1.58204e+06"
"181 970425"
"182 1.37454e+06"
"183 1.57941e+06"
"184 1.56238e+06"
"185 1.5701e+06"
"186 1.43074e+06"
```
Previous (with megatron and apex installed separately):
```
"677264 971882"
"677265 1.12557e+06"
"677266 1.26441e+06"
"677267 1.42306e+06"
"677268 1.11689e+06"
"677269 1.13286e+06"
"677270 1.49057e+06"
"677271 1.31243e+06"
```

**Review by moyapchen — APPROVED** [review]
Stamp

**Pull request merged**
