### PR TITLE
hack update_freq implementation for streaming_language_modeling

### PR DESCRIPTION
**Pull request by todpole3**
Add update_freq to streaming_language_modeling to possibly increase 175B model training size.

### CODE REVIEW

**Comment by ramakanth-pasunuru** [comment]
Looks good to me, but wondering why its not added in the first place for pre-training. 

Did it work fine with update_freq>1?

**Comment by stephenroller** [comment]
Not obvious to me why this can be upstreamed to main with appropriate cleanup

**Comment by todpole3** [comment]
@ramakanth-pasunuru See this workplace discussion -- https://fb.workplace.com/groups/gogogptzusers/permalink/776552453570779; there is no specific reasons blocking this to be added to streaming language models.

**Review by ramakanth-pasunuru — APPROVED** [review]
LGTM

**Pull request merged**
