### PR TITLE
Init for model_parallel == 1

### PR DESCRIPTION
**Pull request by suchenzang**

### CODE REVIEW

**Review by stephenroller — COMMENTED** [review]
i tried this before. iirc the megatron code doesn't do well with it. maybe things have changed since i tried or there's something more subtle going on?

**Comment by suchenzang** [comment]
@stephenroller this diff worked just fine when I tested with mp 1 🤷🏻‍♀️

**Comment by stephenroller** [comment]
is it too much to ask for a test? 😅

**Comment by suchenzang** [comment]
@stephenroller the 125m baseline test already caught something here, since it contains code that requires mp > 1 and transformer_lm arch to work (previously assumed that transformer_lm would never call into mp code). I've kept this test behavior as is, but I would like to redo our transformer_lm / transformer_lm_megatron branching first, because the above shouldn't even be the case in practice (another complication in our reshard logic, it seems).

Separately, we had an 8m baseline test at some point. Do you know where that went?

**Comment by suchenzang** [comment]
Found it - added https://github.com/facebookresearch/metaseq/issues/578 to track this

**Review by stephenroller — APPROVED** [review]

**Pull request merged**
