### PR TITLE
Unify model-parallel vs non model-parallel codepaths

### PR DESCRIPTION
**Pull request by bashnick**
**Patch Description**
Unified model-parallel vs non model-parallel codepaths: merged files from metaseq.model_parallel to metaseq.models. Solving issue #389  

**Testing steps**
MP2
python -m PROJECT.sweep_baseline -g 4 -n 1 --model-size 8m --prefix test_01  --local --data /checkpoint/TEAM_NAME/datasets/consolidated/v4.0

MP1
python -m PROJECT.sweep_baseline -g 4 -n 1 --model-size 8m_mp1 --prefix test_01  --local --data /checkpoint/TEAM_NAME/datasets/consolidated/v4.0

**Results**
MP2
| Metric | Before | After | Comment |
| --- | --- | --- | --- |
| num_updates | 100 | 100 | --- |
| loss | 14.406 | 14.406 | --- |
| wps | 911142 | 909002 | <0.25% difference, noise |

MP=1
| Metric | Before | After | Comment |
| --- | --- | --- | --- |
| num_updates | 100 | 100 | --- |
| loss | 15.857 | 15.857 | --- |

**After merging**

Need to re-install metaseq:
rm -rf metaseq
copy metaseq from main branch
cd ~/rsc/metaseq
pip install --no-build-isolation -e .

### CODE REVIEW

**Comment by suchenzang** [comment]
One more TODO (perhaps for me): 
* resume training from an existing checkpoint to see if that still works as expected
* test if inference on existing checkpoint still works as expected

(don't think either will be affected here, but will need this sanity check to be safe)

**Comment by bashnick** [comment]
> 

Good point, I'll test this as well.

**Comment by suchenzang** [comment]
Ok tested resuming from a previous run and things look good. From the diff, it doesn't seem like any configurations is actually impacted, so approving to move onto the next step!

**Review by suchenzang — APPROVED** [review]

**Comment by bashnick** [comment]
> Ok tested resuming from a previous run and things look good. From the diff, it doesn't seem like any configurations is actually impacted, so approving to move onto the next step!

yes, my next diff would touch on some of the configs, when I combine the model arch: transformer_lm_megatron and transformer_lm arch. #583

**Pull request merged**
