### PR TITLE
Changes flag

### PR DESCRIPTION
**Pull request by sriniiyer**
We need Changes=true during training for doc attention to work. We need Changes=False during eval. This solves this using an environment variable called EVAL.

### CODE REVIEW

**Review by stephenroller — CHANGES_REQUESTED** [review]
Why don't you set it in inference mode at start? That's what the "make_generation_fast_" thing does.

**Comment by stephenroller** [comment]
Or alternatively, why wouldn't we use the break mode arg to choose this logic?

**Review by todpole3 — APPROVED** [review]
lgtm

**Comment by sriniiyer** [comment]
> Why don't you set it in inference mode at start? That's what the "make_generation_fast_" thing does.

Will look into this, using this for now to unblock others

**Pull request merged**
