### PR TITLE
[Cleanup] Delete unused methods / imports / args / classes: 2.1/N

### PR DESCRIPTION
**Pull request by suchenzang**
Splitting https://github.com/facebookresearch/metaseq/pull/231 up into 2 PRs.

Removed:
* unused `moe_disable_padding` arg
* unused `from_pretrained` methods, since we currently depend on `load_model_ensemble_and_task` from `checkpoint_utils` (not great but saving that for another PR)
* unused `hub_models` method
* unused `return_all_hiddens` arg, and no `encoder_states` being returned as a result

### CODE REVIEW

**Comment by stephenroller** [comment]
I guess what i'm confused about is why this PR kills encoder_states instead of moving that to the enc-dec deletion PR. We're having some sort of miscommunication here.

**Comment by suchenzang** [comment]
@stephenroller if that's the one that bugs you, I'll revert that one commit.  Reason this isn't tied to enc-dec deletion is because it originated from deleting an unused flag that gates the entire codepath related to encoder_states.

**Review by stephenroller — APPROVED** [review]

**Comment by stephenroller** [comment]
Thanks for the clarification

**Comment by stephenroller** [comment]
(The reason being that if we do bring back enc dec, the generator will need access to those states usually)

**Pull request merged**
