### PR TITLE
loading model as it is trained

### PR DESCRIPTION
**Pull request by lilisierrayu**
**Patch Description**
Fixing [issue #276](https://github.com/facebookresearch/metaseq/issues/276). Converting model data type when loading states is dangerous. Our model is saved as it is trained, so there is no need to further change the datatype when loading correctly saved models . 

**Testing steps**
Describe how you tested your changes

### CODE REVIEW

**Review by suchenzang — APPROVED** [review]

**Comment by suchenzang** [comment]
Ah damn, looks like gpu test got busted on the HF compatibility test. cc @punitkoura if you have a chance to take a look (I can do this later too)

**Comment by ngoyal2707** [comment]
I *think* you can kill this code as well: https://github.com/facebookresearch/metaseq/blob/main/metaseq/file_io.py#L219-L225

**Comment by punitkoura** [comment]
> Ah damn, looks like gpu test got busted on the HF compatibility test. cc @punitkoura if you have a chance to take a look (I can do this later too)

Looking into this

**Comment by KUNAL1612** [comment]
@punitkoura doesn't .half() change the data type? This looks very similar to the error I faced when I tried to run the convert to singleton script on the 1.3B model, the issue logged in #233

**Comment by punitkoura** [comment]
> @punitkoura doesn't .half() change the data type? This looks very similar to the error I faced when I tried to run the convert to singleton script on the 1.3B model, the issue logged in #233

@KUNAL1612 You're right, I'm just testing it out locally before adding it here.

**Comment by punitkoura** [comment]
@lilisierrayu Could you add these changes to fix the failing test

```diff
diff --git a/gpu_tests/test_hf_compatibility.py b/gpu_tests/test_hf_compatibility.py
index 145c0df..5f3ea64 100644
--- a/gpu_tests/test_hf_compatibility.py
+++ b/gpu_tests/test_hf_compatibility.py
@@ -41,7 +41,8 @@ def load_mp_model_and_run_eval(cfg: MetaseqConfig, **kwargs):
 
     def _build_model(cfg, task):
         # hardcoded to cpu & fp16
-        model = task.build_model(cfg.model).half().cuda()
+        cfg.model.tensor_parallel_init_model_on_gpu = True
+        model = task.build_model(cfg.model).cuda()
         return fsdp_wrap(model)
 
     with fsdp_enable_wrap(
diff --git a/metaseq/scripts/convert_to_singleton.py b/metaseq/scripts/convert_to_singleton.py
index 32d09ef..30a3af0 100644
--- a/metaseq/scripts/convert_to_singleton.py
+++ b/metaseq/scripts/convert_to_singleton.py
@@ -103,7 +103,8 @@ def worker_main(cfg: MetaseqConfig):
 
     def _build_model(cfg, task):
         # hardcoded to cpu & fp16
-        model = task.build_model(cfg.model).half().cuda()
+        cfg.model.tensor_parallel_init_model_on_gpu = True
+        model = task.build_model(cfg.model).cuda()
         return fsdp_wrap(model)
 
     with fsdp_enable_wrap(
```

**Comment by lilisierrayu** [comment]
@punitkoura  changes added! Thank you so much.

**Review by stephenroller — APPROVED** [review]
Tysm I was just about to write this diff!!

Edit I jumped the gun bc I was too excited

**Pull request merged**
