### PR TITLE
Delete Heartbeat Timeout

### PR DESCRIPTION
**Pull request by annavordou**
**Patch Description**
I deleted the file [distributed_timeout_wrapper.py] 
(https://github.com/facebookresearch/metaseq/blob/main/metaseq/distributed/distributed_timeout_wrapper.py) and made changes wherever needed.

### CODE REVIEW

**Review by stephenroller — COMMENTED** [review]
Thanks! Can you also Grep for "heartbeat_timeout" and remove those references?

**Comment by annavordou** [comment]
> Thanks! Can you also Grep for "heartbeat_timeout" and remove those references?

Sure! Should I issue a pull request again afterwords or should I just push the changes?

**Comment by stephenroller** [comment]
You can just push the changes, they'll show up here.

**Comment by stephenroller** [comment]
Okay looks good. I think we just need to delete the cpu test.

**Review by suchenzang — APPROVED** [review]

**Pull request merged**
